-- MySQL Script generated by MySQL Workbench
-- lun. 04 mars 2019 14:34:27 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_fitness
-- -----------------------------------------------------
-- Base de données servant de support au projet chef-d'oeuvre
DROP SCHEMA IF EXISTS `db_fitness` ;

-- -----------------------------------------------------
-- Schema db_fitness
--
-- Base de données servant de support au projet chef-d'oeuvre
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_fitness` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `db_fitness` ;

-- -----------------------------------------------------
-- Table `db_fitness`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Customer` (
  `Users_username` VARCHAR(45) NOT NULL,
  `domesticAddress` VARCHAR(255) NOT NULL,
  `domesticCp` VARCHAR(15) NOT NULL,
  `domesticCity` VARCHAR(45) NOT NULL,
  `domesticCountry` VARCHAR(45) NOT NULL,
  `deliveryAddress` VARCHAR(255) NOT NULL,
  `deliveryCp` VARCHAR(45) NOT NULL,
  `deliveryCity` VARCHAR(45) NOT NULL,
  `deliveryCountry` VARCHAR(45) NOT NULL,
  `dateOfBirthday` DATE NULL,
  PRIMARY KEY (`Users_username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fitness`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Staff` (
  `Users_username` VARCHAR(45) NOT NULL,
  `dayWorking` VARCHAR(45) NULL,
  `hourWorking` VARCHAR(45) NULL,
  PRIMARY KEY (`Users_username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fitness`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Users` (
  `username` VARCHAR(45) NOT NULL,
  `idUser` INT NOT NULL,
  `fullname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(15) NULL,
  `dateOfRegistration` DATE NOT NULL,
  `Customer_Users_username` VARCHAR(45) NULL,
  `Staff_Users_username` VARCHAR(45) NULL,
  PRIMARY KEY (`username`),
  CONSTRAINT `fk_Users_Customer1`
    FOREIGN KEY (`Customer_Users_username`)
    REFERENCES `db_fitness`.`Customer` (`Users_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_Staff1`
    FOREIGN KEY (`Staff_Users_username`)
    REFERENCES `db_fitness`.`Staff` (`Users_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `db_fitness`.`Users` (`email` ASC);

CREATE UNIQUE INDEX `idUser_UNIQUE` ON `db_fitness`.`Users` (`idUser` ASC);

CREATE INDEX `fk_Users_Customer1_idx` ON `db_fitness`.`Users` (`Customer_Users_username` ASC);

CREATE INDEX `fk_Users_Staff1_idx` ON `db_fitness`.`Users` (`Staff_Users_username` ASC);


-- -----------------------------------------------------
-- Table `db_fitness`.`Authorities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Authorities` (
  `Users_username` VARCHAR(45) NOT NULL,
  `authority` VARCHAR(45) NOT NULL DEFAULT 'ROLE_ANONYMOUS',
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Users_username`),
  CONSTRAINT `fk_Authorities_Users1`
    FOREIGN KEY (`Users_username`)
    REFERENCES `db_fitness`.`Users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fitness`.`Subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Subscription` (
  `idSubscriptionType` INT NOT NULL,
  `nameSubscription` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `last` VARCHAR(45) NOT NULL,
  `Customer_Users_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSubscriptionType`),
  CONSTRAINT `fk_Subscription_Customer1`
    FOREIGN KEY (`Customer_Users_username`)
    REFERENCES `db_fitness`.`Customer` (`Users_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Subscription_Customer1_idx` ON `db_fitness`.`Subscription` (`Customer_Users_username` ASC);


-- -----------------------------------------------------
-- Table `db_fitness`.`ConnectedWatch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`ConnectedWatch` (
  `idConnectedWatch` INT NOT NULL,
  `modelWatch` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `Customer_Users_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idConnectedWatch`),
  CONSTRAINT `fk_ConnectedWatch_Customer1`
    FOREIGN KEY (`Customer_Users_username`)
    REFERENCES `db_fitness`.`Customer` (`Users_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ConnectedWatch_Customer1_idx` ON `db_fitness`.`ConnectedWatch` (`Customer_Users_username` ASC);


-- -----------------------------------------------------
-- Table `db_fitness`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Room` (
  `idRoom` INT NOT NULL,
  `roomName` VARCHAR(45) NULL,
  `capacity` INT NOT NULL,
  PRIMARY KEY (`idRoom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fitness`.`FacilityCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`FacilityCategory` (
  `idFacilityCategory` INT NOT NULL,
  `facilityCategoryName` VARCHAR(45) NOT NULL,
  `quantity` INT NULL,
  `price` FLOAT NULL,
  `description` LONGTEXT NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`idFacilityCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fitness`.`Facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Facility` (
  `idFacility` INT NOT NULL,
  `facilityName` VARCHAR(45) NOT NULL,
  `Room_idRoom` INT NOT NULL,
  `FacilityCategory_idFacilityCategory` INT NOT NULL,
  PRIMARY KEY (`idFacility`),
  CONSTRAINT `fk_Equipement_Room1`
    FOREIGN KEY (`Room_idRoom`)
    REFERENCES `db_fitness`.`Room` (`idRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Facility_FacilityCategory1`
    FOREIGN KEY (`FacilityCategory_idFacilityCategory`)
    REFERENCES `db_fitness`.`FacilityCategory` (`idFacilityCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Equipement_Room1_idx` ON `db_fitness`.`Facility` (`Room_idRoom` ASC);

CREATE UNIQUE INDEX `nameMaterial_UNIQUE` ON `db_fitness`.`Facility` (`facilityName` ASC);

CREATE INDEX `fk_Facility_FacilityCategory1_idx` ON `db_fitness`.`Facility` (`FacilityCategory_idFacilityCategory` ASC);


-- -----------------------------------------------------
-- Table `db_fitness`.`Purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Purchase` (
  `idPrestation` INT NOT NULL,
  `price` FLOAT NOT NULL,
  `Users_username` VARCHAR(45) NOT NULL,
  `Subscription_idSubscriptionType` INT NULL,
  `ConnectedWatch_idConnectedWatch` INT NULL,
  `dateOfPurchase` DATETIME NOT NULL,
  PRIMARY KEY (`idPrestation`),
  CONSTRAINT `fk_Prestation_Users1`
    FOREIGN KEY (`Users_username`)
    REFERENCES `db_fitness`.`Users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestation_Subscription1`
    FOREIGN KEY (`Subscription_idSubscriptionType`)
    REFERENCES `db_fitness`.`Subscription` (`idSubscriptionType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestation_ConnectedWatch1`
    FOREIGN KEY (`ConnectedWatch_idConnectedWatch`)
    REFERENCES `db_fitness`.`ConnectedWatch` (`idConnectedWatch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Prestation_Users1_idx` ON `db_fitness`.`Purchase` (`Users_username` ASC);

CREATE INDEX `fk_Prestation_Subscription1_idx` ON `db_fitness`.`Purchase` (`Subscription_idSubscriptionType` ASC);

CREATE INDEX `fk_Prestation_ConnectedWatch1_idx` ON `db_fitness`.`Purchase` (`ConnectedWatch_idConnectedWatch` ASC);


-- -----------------------------------------------------
-- Table `db_fitness`.`Seance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Seance` (
  `idSeance` INT NOT NULL,
  `Purchase_idPrestation` INT NOT NULL,
  `Customer_Users_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSeance`),
  CONSTRAINT `fk_Seance_Purchase1`
    FOREIGN KEY (`Purchase_idPrestation`)
    REFERENCES `db_fitness`.`Purchase` (`idPrestation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seance_Customer1`
    FOREIGN KEY (`Customer_Users_username`)
    REFERENCES `db_fitness`.`Customer` (`Users_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Seance_Purchase1_idx` ON `db_fitness`.`Seance` (`Purchase_idPrestation` ASC);

CREATE INDEX `fk_Seance_Customer1_idx` ON `db_fitness`.`Seance` (`Customer_Users_username` ASC);


-- -----------------------------------------------------
-- Table `db_fitness`.`SessionTraining`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`SessionTraining` (
  `idSessionTraining` INT NOT NULL,
  `dateTime` DATETIME NOT NULL,
  `capacityAttendant` INT NOT NULL,
  `Staff_Users_username` VARCHAR(45) NOT NULL,
  `Room_idRoom` INT NOT NULL,
  PRIMARY KEY (`idSessionTraining`),
  CONSTRAINT `fk_SessionTraining_Staff1`
    FOREIGN KEY (`Staff_Users_username`)
    REFERENCES `db_fitness`.`Staff` (`Users_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SessionTraining_Room1`
    FOREIGN KEY (`Room_idRoom`)
    REFERENCES `db_fitness`.`Room` (`idRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_SessionTraining_Staff1_idx` ON `db_fitness`.`SessionTraining` (`Staff_Users_username` ASC);

CREATE INDEX `fk_SessionTraining_Room1_idx` ON `db_fitness`.`SessionTraining` (`Room_idRoom` ASC);


-- -----------------------------------------------------
-- Table `db_fitness`.`Command`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Command` (
  `idCommande` INT NOT NULL,
  `dateTime` DATETIME NULL,
  `totalPrice` FLOAT NULL,
  PRIMARY KEY (`idCommande`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fitness`.`SessionTraining_has_Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`SessionTraining_has_Customer` (
  `SessionTraining_idSessionTraining` INT NOT NULL,
  `Customer_Users_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SessionTraining_idSessionTraining`, `Customer_Users_username`),
  CONSTRAINT `fk_SessionTraining_has_Customer_SessionTraining1`
    FOREIGN KEY (`SessionTraining_idSessionTraining`)
    REFERENCES `db_fitness`.`SessionTraining` (`idSessionTraining`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SessionTraining_has_Customer_Customer1`
    FOREIGN KEY (`Customer_Users_username`)
    REFERENCES `db_fitness`.`Customer` (`Users_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_SessionTraining_has_Customer_Customer1_idx` ON `db_fitness`.`SessionTraining_has_Customer` (`Customer_Users_username` ASC);

CREATE INDEX `fk_SessionTraining_has_Customer_SessionTraining1_idx` ON `db_fitness`.`SessionTraining_has_Customer` (`SessionTraining_idSessionTraining` ASC);


-- -----------------------------------------------------
-- Table `db_fitness`.`Purchase_has_Command`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Purchase_has_Command` (
  `Purchase_idPrestation` INT NOT NULL,
  `Command_idCommande` INT NOT NULL,
  PRIMARY KEY (`Purchase_idPrestation`, `Command_idCommande`),
  CONSTRAINT `fk_Purchase_has_Command_Purchase1`
    FOREIGN KEY (`Purchase_idPrestation`)
    REFERENCES `db_fitness`.`Purchase` (`idPrestation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_has_Command_Command1`
    FOREIGN KEY (`Command_idCommande`)
    REFERENCES `db_fitness`.`Command` (`idCommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Purchase_has_Command_Command1_idx` ON `db_fitness`.`Purchase_has_Command` (`Command_idCommande` ASC);

CREATE INDEX `fk_Purchase_has_Command_Purchase1_idx` ON `db_fitness`.`Purchase_has_Command` (`Purchase_idPrestation` ASC);


-- -----------------------------------------------------
-- Table `db_fitness`.`Purchase_has_SessionTraining`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Purchase_has_SessionTraining` (
  `Purchase_idPrestation` INT NOT NULL,
  `SessionTraining_idSessionTraining` INT NOT NULL,
  PRIMARY KEY (`Purchase_idPrestation`, `SessionTraining_idSessionTraining`),
  CONSTRAINT `fk_Purchase_has_SessionTraining_Purchase1`
    FOREIGN KEY (`Purchase_idPrestation`)
    REFERENCES `db_fitness`.`Purchase` (`idPrestation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_has_SessionTraining_SessionTraining1`
    FOREIGN KEY (`SessionTraining_idSessionTraining`)
    REFERENCES `db_fitness`.`SessionTraining` (`idSessionTraining`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Purchase_has_SessionTraining_SessionTraining1_idx` ON `db_fitness`.`Purchase_has_SessionTraining` (`SessionTraining_idSessionTraining` ASC);

CREATE INDEX `fk_Purchase_has_SessionTraining_Purchase1_idx` ON `db_fitness`.`Purchase_has_SessionTraining` (`Purchase_idPrestation` ASC);


-- -----------------------------------------------------
-- Table `db_fitness`.`TimestampFacility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`TimestampFacility` (
  `idTimestampFacillity` INT NOT NULL,
  `refTimestamp` VARCHAR(45) NOT NULL,
  `Facility_idFacility` INT NOT NULL,
  PRIMARY KEY (`idTimestampFacillity`),
  CONSTRAINT `fk_TimestampFacility_Facility1`
    FOREIGN KEY (`Facility_idFacility`)
    REFERENCES `db_fitness`.`Facility` (`idFacility`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TimestampFacility_Facility1_idx` ON `db_fitness`.`TimestampFacility` (`Facility_idFacility` ASC);


-- -----------------------------------------------------
-- Table `db_fitness`.`MaintenanceOperation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`MaintenanceOperation` (
  `idMaintenanceOperation` INT NOT NULL,
  `cost` FLOAT NULL,
  `dateOfIntervention` DATETIME NULL,
  `Facility_idFacility` INT NOT NULL,
  PRIMARY KEY (`idMaintenanceOperation`),
  CONSTRAINT `fk_MaintenanceOperation_Facility1`
    FOREIGN KEY (`Facility_idFacility`)
    REFERENCES `db_fitness`.`Facility` (`idFacility`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_MaintenanceOperation_Facility1_idx` ON `db_fitness`.`MaintenanceOperation` (`Facility_idFacility` ASC);


-- -----------------------------------------------------
-- Table `db_fitness`.`Seance_has_TimestampFacility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Seance_has_TimestampFacility` (
  `Seance_idSeance` INT NOT NULL,
  `TimestampFacility_idTimestampFacillity` INT NOT NULL,
  PRIMARY KEY (`Seance_idSeance`, `TimestampFacility_idTimestampFacillity`),
  CONSTRAINT `fk_Seance_has_TimestampFacility_Seance1`
    FOREIGN KEY (`Seance_idSeance`)
    REFERENCES `db_fitness`.`Seance` (`idSeance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seance_has_TimestampFacility_TimestampFacility1`
    FOREIGN KEY (`TimestampFacility_idTimestampFacillity`)
    REFERENCES `db_fitness`.`TimestampFacility` (`idTimestampFacillity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Seance_has_TimestampFacility_TimestampFacility1_idx` ON `db_fitness`.`Seance_has_TimestampFacility` (`TimestampFacility_idTimestampFacillity` ASC);

CREATE INDEX `fk_Seance_has_TimestampFacility_Seance1_idx` ON `db_fitness`.`Seance_has_TimestampFacility` (`Seance_idSeance` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
