-- MySQL Script generated by MySQL Workbench
-- Thu Feb 28 15:26:26 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_fitness
-- -----------------------------------------------------
-- Base de données servant de support au projet chef-d'oeuvre
DROP SCHEMA IF EXISTS `db_fitness` ;

-- -----------------------------------------------------
-- Schema db_fitness
--
-- Base de données servant de support au projet chef-d'oeuvre
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_fitness` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `db_fitness` ;

-- -----------------------------------------------------
-- Table `db_fitness`.`Authorities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Authorities` (
  `username` VARCHAR(45) NOT NULL,
  `authority` VARCHAR(45) NULL DEFAULT 'ROLE_ANONYMOUS',
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fitness`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Users` (
  `idUser` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `fullname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `tel` VARCHAR(15) NULL,
  `creationDate` DATETIME NULL,
  `enabled` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`username`),
  CONSTRAINT `fk_Users_Authorities1`
    FOREIGN KEY (`username`)
    REFERENCES `db_fitness`.`Authorities` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `db_fitness`.`Users` (`email` ASC) VISIBLE;

CREATE INDEX `fk_Users_Authorities1_idx` ON `db_fitness`.`Users` (`username` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_fitness`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Customer` (
  `idCustomer` INT NOT NULL,
  `domesticAddress` VARCHAR(255) NULL,
  `domesticCp` VARCHAR(15) NULL,
  `domesticCity` VARCHAR(45) NULL,
  `domesticCountry` VARCHAR(45) NULL,
  `deliveryAddress` VARCHAR(255) NULL,
  `deliveryCp` VARCHAR(45) NULL,
  `deliveryCity` VARCHAR(45) NULL,
  `deliveryCountry` VARCHAR(45) NULL,
  `modelWatch` VARCHAR(45) NULL,
  `typeSubscription` VARCHAR(45) NULL,
  `Users_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCustomer`),
  CONSTRAINT `fk_Customer_Users1`
    FOREIGN KEY (`Users_username`)
    REFERENCES `db_fitness`.`Users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Customer_Users1_idx` ON `db_fitness`.`Customer` (`Users_username` ASC) VISIBLE;

CREATE UNIQUE INDEX `Users_username_UNIQUE` ON `db_fitness`.`Customer` (`Users_username` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_fitness`.`ConnectedWatchModel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`ConnectedWatchModel` (
  `idConnectedWatchModel` INT NOT NULL,
  `modelWatch` VARCHAR(45) NULL,
  `price` FLOAT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`idConnectedWatchModel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fitness`.`Prestation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Prestation` (
  `idPrestation` INT NOT NULL,
  `price` FLOAT NULL,
  `Users_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPrestation`),
  CONSTRAINT `fk_Prestation_Users1`
    FOREIGN KEY (`Users_username`)
    REFERENCES `db_fitness`.`Users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Prestation_Users1_idx` ON `db_fitness`.`Prestation` (`Users_username` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_fitness`.`ConnectedWatch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`ConnectedWatch` (
  `idConnectedWatch` INT NOT NULL,
  `ConnectedWatchModel_idConnectedWatchModel` INT NOT NULL,
  `Users_username` VARCHAR(45) NOT NULL,
  `Prestation_idPrestation` INT NOT NULL,
  `Customer_idCustomer` INT NOT NULL,
  PRIMARY KEY (`idConnectedWatch`),
  CONSTRAINT `fk_ConnectedWatch_ConnectedWatchModel1`
    FOREIGN KEY (`ConnectedWatchModel_idConnectedWatchModel`)
    REFERENCES `db_fitness`.`ConnectedWatchModel` (`idConnectedWatchModel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConnectedWatch_Prestation1`
    FOREIGN KEY (`Prestation_idPrestation`)
    REFERENCES `db_fitness`.`Prestation` (`idPrestation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConnectedWatch_Customer1`
    FOREIGN KEY (`Customer_idCustomer`)
    REFERENCES `db_fitness`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ConnectedWatch_ConnectedWatchModel1_idx` ON `db_fitness`.`ConnectedWatch` (`ConnectedWatchModel_idConnectedWatchModel` ASC) VISIBLE;

CREATE INDEX `fk_ConnectedWatch_Prestation1_idx` ON `db_fitness`.`ConnectedWatch` (`Prestation_idPrestation` ASC) VISIBLE;

CREATE INDEX `fk_ConnectedWatch_Customer1_idx` ON `db_fitness`.`ConnectedWatch` (`Customer_idCustomer` ASC) VISIBLE;

CREATE UNIQUE INDEX `Customer_idCustomer_UNIQUE` ON `db_fitness`.`ConnectedWatch` (`Customer_idCustomer` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_fitness`.`SubscriptionModel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`SubscriptionModel` (
  `idSubscriptionType` INT NOT NULL,
  `nameSubscription` VARCHAR(45) NULL,
  `price` FLOAT NULL,
  `last` VARCHAR(45) NULL,
  PRIMARY KEY (`idSubscriptionType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fitness`.`Subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Subscription` (
  `idSubscription` INT NOT NULL,
  `SubscriptionModel_idSubscriptionType` INT NOT NULL,
  `Users_username` VARCHAR(45) NOT NULL,
  `Prestation_idPrestation` INT NOT NULL,
  PRIMARY KEY (`idSubscription`),
  CONSTRAINT `fk_Subscription_SubscriptionModel1`
    FOREIGN KEY (`SubscriptionModel_idSubscriptionType`)
    REFERENCES `db_fitness`.`SubscriptionModel` (`idSubscriptionType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subscription_Prestation1`
    FOREIGN KEY (`Prestation_idPrestation`)
    REFERENCES `db_fitness`.`Prestation` (`idPrestation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Subscription_SubscriptionModel1_idx` ON `db_fitness`.`Subscription` (`SubscriptionModel_idSubscriptionType` ASC) VISIBLE;

CREATE INDEX `fk_Subscription_Prestation1_idx` ON `db_fitness`.`Subscription` (`Prestation_idPrestation` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_fitness`.`EquipementModel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`EquipementModel` (
  `idEquipementModel` INT NOT NULL,
  `nameEquipement` VARCHAR(45) NULL,
  `categoryEquipement` VARCHAR(45) NULL,
  `quantity` VARCHAR(45) NULL,
  PRIMARY KEY (`idEquipementModel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fitness`.`Equipement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Equipement` (
  `idEquipement` INT NOT NULL,
  `timestamp` VARCHAR(45) NOT NULL,
  `nameEquipement` VARCHAR(45) NULL,
  `seance` VARCHAR(45) NULL,
  `EquipementModel_idEquipementModel` INT NOT NULL,
  PRIMARY KEY (`idEquipement`),
  CONSTRAINT `fk_Equipement_EquipementModel1`
    FOREIGN KEY (`EquipementModel_idEquipementModel`)
    REFERENCES `db_fitness`.`EquipementModel` (`idEquipementModel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `timestamp_UNIQUE` ON `db_fitness`.`Equipement` (`timestamp` ASC) VISIBLE;

CREATE INDEX `fk_Equipement_EquipementModel1_idx` ON `db_fitness`.`Equipement` (`EquipementModel_idEquipementModel` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_fitness`.`Seance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Seance` (
  `idSeance` INT NOT NULL,
  `Prestation_idPrestation` INT NOT NULL,
  PRIMARY KEY (`idSeance`),
  CONSTRAINT `fk_Seance_Prestation1`
    FOREIGN KEY (`Prestation_idPrestation`)
    REFERENCES `db_fitness`.`Prestation` (`idPrestation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Seance_Prestation1_idx` ON `db_fitness`.`Seance` (`Prestation_idPrestation` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_fitness`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Room` (
  `idRoom` INT NOT NULL,
  `capacity` INT NULL,
  `Equipement_idEquipement` INT NOT NULL,
  PRIMARY KEY (`idRoom`),
  CONSTRAINT `fk_Room_Equipement1`
    FOREIGN KEY (`Equipement_idEquipement`)
    REFERENCES `db_fitness`.`Equipement` (`idEquipement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Room_Equipement1_idx` ON `db_fitness`.`Room` (`Equipement_idEquipement` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_fitness`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Staff` (
  `idStaff` INT NOT NULL,
  `dayWorking` VARCHAR(45) NULL,
  `hourWorking` VARCHAR(45) NULL,
  `Users_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStaff`),
  CONSTRAINT `fk_Staff_Users1`
    FOREIGN KEY (`Users_username`)
    REFERENCES `db_fitness`.`Users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Staff_Users1_idx` ON `db_fitness`.`Staff` (`Users_username` ASC) VISIBLE;

CREATE UNIQUE INDEX `Users_username_UNIQUE` ON `db_fitness`.`Staff` (`Users_username` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_fitness`.`SessionTraining`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`SessionTraining` (
  `idSessionTraining` INT NOT NULL,
  `dateTime` DATETIME NULL,
  `attendant` INT NULL,
  `Prestation_idPrestation` INT NOT NULL,
  `Staff_idStaff` INT NOT NULL,
  `Room_idRoom` INT NOT NULL,
  PRIMARY KEY (`idSessionTraining`),
  CONSTRAINT `fk_SessionTraining_Prestation1`
    FOREIGN KEY (`Prestation_idPrestation`)
    REFERENCES `db_fitness`.`Prestation` (`idPrestation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SessionTraining_Staff1`
    FOREIGN KEY (`Staff_idStaff`)
    REFERENCES `db_fitness`.`Staff` (`idStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SessionTraining_Room1`
    FOREIGN KEY (`Room_idRoom`)
    REFERENCES `db_fitness`.`Room` (`idRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_SessionTraining_Prestation1_idx` ON `db_fitness`.`SessionTraining` (`Prestation_idPrestation` ASC) VISIBLE;

CREATE INDEX `fk_SessionTraining_Staff1_idx` ON `db_fitness`.`SessionTraining` (`Staff_idStaff` ASC) VISIBLE;

CREATE INDEX `fk_SessionTraining_Room1_idx` ON `db_fitness`.`SessionTraining` (`Room_idRoom` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_fitness`.`Seance_has_Equipement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Seance_has_Equipement` (
  `Seance_idSeance` INT NOT NULL,
  `Equipement_idEquipement` INT NOT NULL,
  `timestamp` VARCHAR(45) NULL,
  PRIMARY KEY (`Seance_idSeance`, `Equipement_idEquipement`),
  CONSTRAINT `fk_Seance_has_Equipement_Seance1`
    FOREIGN KEY (`Seance_idSeance`)
    REFERENCES `db_fitness`.`Seance` (`idSeance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seance_has_Equipement_Equipement1`
    FOREIGN KEY (`Equipement_idEquipement`)
    REFERENCES `db_fitness`.`Equipement` (`idEquipement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Seance_has_Equipement_Equipement1_idx` ON `db_fitness`.`Seance_has_Equipement` (`Equipement_idEquipement` ASC) VISIBLE;

CREATE INDEX `fk_Seance_has_Equipement_Seance1_idx` ON `db_fitness`.`Seance_has_Equipement` (`Seance_idSeance` ASC) VISIBLE;

CREATE UNIQUE INDEX `timestamp_UNIQUE` ON `db_fitness`.`Seance_has_Equipement` (`timestamp` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_fitness`.`Commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Commande` (
  `idCommande` INT NOT NULL,
  `dateTime` DATETIME NULL,
  `totalPrice` FLOAT NULL,
  PRIMARY KEY (`idCommande`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_fitness`.`Commande_has_Prestation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_fitness`.`Commande_has_Prestation` (
  `Commande_idCommande` INT NOT NULL,
  `Prestation_idPrestation` INT NOT NULL,
  PRIMARY KEY (`Commande_idCommande`, `Prestation_idPrestation`),
  CONSTRAINT `fk_Commande_has_Prestation_Commande1`
    FOREIGN KEY (`Commande_idCommande`)
    REFERENCES `db_fitness`.`Commande` (`idCommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_has_Prestation_Prestation1`
    FOREIGN KEY (`Prestation_idPrestation`)
    REFERENCES `db_fitness`.`Prestation` (`idPrestation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Commande_has_Prestation_Prestation1_idx` ON `db_fitness`.`Commande_has_Prestation` (`Prestation_idPrestation` ASC) VISIBLE;

CREATE INDEX `fk_Commande_has_Prestation_Commande1_idx` ON `db_fitness`.`Commande_has_Prestation` (`Commande_idCommande` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
